import { createContext, useContext, useState } from 'react'

const LangContext = createContext(null)

export const translations = {
  en: {
    // Nav
    nav_buy: 'Buy', nav_sell: 'Sell', nav_rent: 'Rent',
    nav_invest: 'Invest', nav_features: 'Features',
    nav_story: 'Our Story', nav_contact: 'Contact',
    nav_account: 'My Account', nav_login: 'Login',
    // Hero
    hero_tag: "Tunisia's First Real Estate Exchange",
    hero_h1_1: 'Real Estate,', hero_h1_2: 'Accessible.',
    hero_sub: 'Invest in Tunisian REITs on the TSE, rent or sell — all in one platform.',
    hero_search: 'Search a city, neighbourhood...',
    hero_search_btn: 'Search',
    hero_cta1: 'Explore REITs', hero_cta2: 'View Rentals',
    // Services
    services_label: 'Our Services', services_h2_1: 'One platform,', services_h2_2: 'three ways to act.',
    svc_sell_title: 'Sell', svc_sell_desc: 'Offload your property immediately. We package it into an exchange-listed REIT — no waiting for a buyer.',
    svc_sell_cta: 'List a Property',
    svc_rent_title: 'Rent', svc_rent_desc: 'Browse hundreds of verified homes across Tunis, Sousse, Sfax and beyond. Transparent prices, 100% online applications.',
    svc_rent_cta: 'Find a Home',
    svc_invest_title: 'Invest', svc_invest_desc: 'Buy REIT shares listed on the TSE. Earn quarterly dividends. Accumulate shares and convert them into full ownership.',
    svc_invest_cta: 'Explore REITs',
    // Invest page
    invest_disclaimer_title: 'Legal Disclaimer',
    invest_disclaimer_p1: 'The information provided is for informational and educational purposes only. It does not constitute financial, legal, or investment advice. Investing in REITs involves risk, including the possible loss of principal.',
    invest_disclaimer_p2: 'Past performance is not indicative of future results. Share prices and dividend income may go down as well as up. Consider your investment objectives, experience, and risk appetite before investing.',
    invest_disclaimer_confirm: 'By continuing, you acknowledge that you have read, understood, and agreed to the terms of this disclaimer.',
    invest_disclaimer_btn: 'I Understand — Continue to Invest',
    invest_h1: 'Invest in Real Estate.', invest_h1_span: 'From Any Budget.',
    invest_sub: 'Buy shares in Tunisian REITs listed on the Tunis Stock Exchange.',
    invest_simulator: 'Investment Simulator', invest_sim_sub: 'Estimate your returns before you invest.',
    invest_amount: 'Investment Amount (TND)', invest_duration: 'Duration',
    invest_rate: 'Annual Return (%)', invest_reinvest: 'Dividend Reinvestment',
    invest_reinvest_yes: 'Yes — Reinvest dividends', invest_reinvest_no: 'No — Receive as cash',
    invest_calc: 'Calculate Returns', invest_results: 'Estimated Results',
    invest_initial: 'Initial Investment', invest_returns: 'Total Returns',
    invest_final: 'Final Portfolio Value', invest_dividend: 'Annual Dividend Income',
    invest_sim_note: '* Simulation only. Actual returns may vary.',
    invest_find: 'Find Your Investment', invest_filter_sub: 'Filter REIT listings by your preferences.',
    invest_showing: 'Showing', invest_reits: 'REIT(s) matching your criteria.',
    invest_no_reits: 'No REITs match your current filters. Try adjusting the criteria above.',
    invest_risk: 'Risk Profile', invest_all_risk: 'All Risk Levels',
    invest_low: 'Low Risk', invest_medium: 'Medium Risk', invest_high: 'High Risk',
    invest_type: 'Property Type', invest_all_types: 'All Types',
    invest_max_price: 'Max Share Price',
    invest_location: 'Location', invest_all_regions: 'All Regions',
    invest_clear: 'Clear', invest_buy_shares: 'Buy Shares',
    invest_share_price: 'Share Price', invest_per_share: '/ share',
    invest_annual_return: 'Annual Return', invest_risk_label: 'Risk',
    invest_num_shares: 'Number of Shares',
    invest_price_per: 'Price per share', invest_shares: 'Shares',
    invest_total: 'Total', invest_balance: 'Your balance',
    invest_login_buy: 'Login to Buy',
    // Account
    acc_portfolio: 'Portfolio', acc_transactions: 'Transactions',
    acc_listings: 'My Listings', acc_rentals: 'Rentals',
    acc_settings: 'Settings', acc_signout: 'Sign Out',
    acc_available: 'Available Cash', acc_recharge: '+ Top Up',
    acc_portfolio_value: 'Portfolio Value', acc_invested: 'Total Invested',
    acc_gain: 'Gain / Loss', acc_income: 'Est. Annual Income',
    acc_holdings: 'Holdings', acc_invest_btn: '+ Invest',
    acc_no_holdings: 'No holdings yet.',
    acc_explore: 'Explore REITs →',
    acc_add_funds: '+ Add Funds', acc_add_funds_title: 'Add Funds',
    acc_current_balance: 'Current balance',
    acc_custom_amount: 'Custom amount (TND)',
    acc_new_balance: 'New balance after deposit',
    acc_add_btn: 'Add', acc_processing: 'Processing...',
    acc_sim_note: 'Simulation only — no real payment.',
    // FAQ
    faq_title: 'Frequently Asked Questions',
    // Contact
    contact_label: 'Contact', contact_h2: 'Get in Touch',
    contact_sub: 'Investor, developer or simply curious — our team will respond within 24 hours.',
    contact_first: 'First Name', contact_last: 'Last Name',
    contact_email: 'Email', contact_profile: 'I am a...',
    contact_select: 'Select your profile', contact_message: 'Message',
    contact_send: 'Send Message', contact_sending: 'Sending...',
    // Affordability
    aff_label: 'Planning Tool', aff_h2: 'Budget Estimator',
    aff_income: 'Monthly Income (TND)', aff_rate: 'Interest Rate (%)',
    aff_years: 'Term (years)', aff_down: 'Down Payment (TND)',
    aff_calc: 'Calculate', aff_results: 'Your Estimate',
    aff_monthly: 'Max monthly payment', aff_loan: 'Loan amount',
    aff_price: 'Property budget', aff_note: 'Keep housing under 35% of net income.',
    aff_placeholder: 'Fill in the form and click Calculate.',
  },
  fr: {
    nav_buy: 'Acheter', nav_sell: 'Vendre', nav_rent: 'Louer',
    nav_invest: 'Investir', nav_features: 'Fonctionnalités',
    nav_story: 'Notre Histoire', nav_contact: 'Contact',
    nav_account: 'Mon Compte', nav_login: 'Connexion',
    hero_tag: 'Première Bourse Immobilière de Tunisie',
    hero_h1_1: 'L\'Immobilier', hero_h1_2: 'Accessible.',
    hero_sub: 'Investissez dans des REITs tunisiens cotés sur la TSE, louez ou vendez — sur une seule plateforme.',
    hero_search: 'Cherchez une ville, un quartier...',
    hero_search_btn: 'Rechercher',
    hero_cta1: 'Explorer les REITs', hero_cta2: 'Voir les Locations',
    services_label: 'Nos Services', services_h2_1: 'Une plateforme,', services_h2_2: 'trois façons d\'agir.',
    svc_sell_title: 'Vendre', svc_sell_desc: 'Cédez votre bien immédiatement. Nous l\'intégrons dans un REIT coté en bourse — sans attendre d\'acheteur.',
    svc_sell_cta: 'Mettre en vente',
    svc_rent_title: 'Louer', svc_rent_desc: 'Parcourez des centaines de logements vérifiés à Tunis, Sousse, Sfax et au-delà. Prix transparents, candidatures 100% en ligne.',
    svc_rent_cta: 'Trouver un logement',
    svc_invest_title: 'Investir', svc_invest_desc: 'Achetez des parts de REITs cotés sur la TSE. Percevez des dividendes trimestriels. Accumulez des parts et convertissez-les en propriété.',
    svc_invest_cta: 'Explorer les REITs',
    invest_disclaimer_title: 'Avertissement Légal',
    invest_disclaimer_p1: 'Les informations fournies sont à titre informatif et éducatif uniquement. Elles ne constituent pas un conseil financier, juridique ou d\'investissement. Investir dans des REITs comporte des risques, notamment la perte en capital.',
    invest_disclaimer_p2: 'Les performances passées ne préjugent pas des résultats futurs. Les prix des parts et les dividendes peuvent évoluer à la hausse comme à la baisse. Prenez en compte vos objectifs, votre expérience et votre tolérance au risque avant d\'investir.',
    invest_disclaimer_confirm: 'En continuant, vous reconnaissez avoir lu, compris et accepté les termes de cet avertissement.',
    invest_disclaimer_btn: 'J\'ai compris — Accéder à la plateforme',
    invest_h1: 'Investissez dans l\'Immobilier.', invest_h1_span: 'Dès n\'importe quel budget.',
    invest_sub: 'Achetez des parts de REITs tunisiens cotés sur la Bourse de Tunis.',
    invest_simulator: 'Simulateur d\'Investissement', invest_sim_sub: 'Estimez vos rendements avant d\'investir.',
    invest_amount: 'Montant (TND)', invest_duration: 'Durée',
    invest_rate: 'Rendement annuel (%)', invest_reinvest: 'Réinvestissement',
    invest_reinvest_yes: 'Oui — Réinvestir les dividendes', invest_reinvest_no: 'Non — Recevoir en espèces',
    invest_calc: 'Calculer', invest_results: 'Résultats Estimés',
    invest_initial: 'Investissement initial', invest_returns: 'Rendement total',
    invest_final: 'Valeur finale du portefeuille', invest_dividend: 'Revenu annuel estimé',
    invest_sim_note: '* Simulation uniquement. Les rendements réels peuvent varier.',
    invest_find: 'Trouvez Votre Investissement', invest_filter_sub: 'Filtrez les REITs selon vos préférences.',
    invest_showing: 'Affichage de', invest_reits: 'REIT(s) correspondant à vos critères.',
    invest_no_reits: 'Aucun REIT ne correspond à vos filtres. Modifiez les critères ci-dessus.',
    invest_risk: 'Profil de Risque', invest_all_risk: 'Tous les niveaux',
    invest_low: 'Risque faible', invest_medium: 'Risque moyen', invest_high: 'Risque élevé',
    invest_type: 'Type de bien', invest_all_types: 'Tous les types',
    invest_max_price: 'Prix max par part',
    invest_location: 'Localisation', invest_all_regions: 'Toutes les régions',
    invest_clear: 'Effacer', invest_buy_shares: 'Acheter des Parts',
    invest_share_price: 'Prix par part', invest_per_share: '/ part',
    invest_annual_return: 'Rendement annuel', invest_risk_label: 'Risque',
    invest_num_shares: 'Nombre de parts',
    invest_price_per: 'Prix par part', invest_shares: 'Parts',
    invest_total: 'Total', invest_balance: 'Votre solde',
    invest_login_buy: 'Connectez-vous pour acheter',
    acc_portfolio: 'Portfolio', acc_transactions: 'Transactions',
    acc_listings: 'Mes Annonces', acc_rentals: 'Locations',
    acc_settings: 'Paramètres', acc_signout: 'Se déconnecter',
    acc_available: 'Solde disponible', acc_recharge: '+ Recharger',
    acc_portfolio_value: 'Valeur du Portfolio', acc_invested: 'Total Investi',
    acc_gain: 'Gain / Perte', acc_income: 'Revenu Annuel Est.',
    acc_holdings: 'Mes Positions', acc_invest_btn: '+ Investir',
    acc_no_holdings: 'Aucun investissement.',
    acc_explore: 'Explorer les REITs →',
    acc_add_funds: '+ Ajouter des Fonds', acc_add_funds_title: 'Ajouter des Fonds',
    acc_current_balance: 'Solde actuel',
    acc_custom_amount: 'Montant personnalisé (TND)',
    acc_new_balance: 'Nouveau solde après dépôt',
    acc_add_btn: 'Ajouter', acc_processing: 'Traitement...',
    acc_sim_note: 'Simulation uniquement — aucun paiement réel.',
    faq_title: 'Questions Fréquentes',
    contact_label: 'Contact', contact_h2: 'Prenons Contact',
    contact_sub: 'Investisseur, promoteur ou simplement curieux — notre équipe vous répondra sous 24h.',
    contact_first: 'Prénom', contact_last: 'Nom',
    contact_email: 'Email', contact_profile: 'Je suis...',
    contact_select: 'Sélectionnez votre profil', contact_message: 'Message',
    contact_send: 'Envoyer', contact_sending: 'Envoi...',
    aff_label: 'Outil de Planification', aff_h2: 'Estimateur de Budget',
    aff_income: 'Revenu mensuel (TND)', aff_rate: 'Taux d\'intérêt (%)',
    aff_years: 'Durée (années)', aff_down: 'Apport (TND)',
    aff_calc: 'Calculer', aff_results: 'Votre Estimation',
    aff_monthly: 'Mensualité maximale', aff_loan: 'Montant empruntable',
    aff_price: 'Budget propriété', aff_note: 'Gardez votre mensualité sous 35% du revenu net.',
    aff_placeholder: 'Remplissez le formulaire et cliquez sur Calculer.',
  }
}

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('estateex-lang') || 'fr')
  const t = translations[lang]
  const toggleLang = () => {
    const next = lang === 'fr' ? 'en' : 'fr'
    setLang(next)
    localStorage.setItem('estateex-lang', next)
  }
  return (
    <LangContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LangContext.Provider>
  )
}

export const useLang = () => useContext(LangContext)
